import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Topo from "@/components/topo/topo";
import React, {useState , useRef, useEffect} from "react";
import { nav } from "@/components/nav/nav";
import { array } from "@/components/nav/objCard";
import SectionCafe from "@/components/SectionCafe/sectionCafe";
import SobreNos from "@/components/sectionSobreNos/sobreNos";
import Menu from "@/components/Menu/menu";
import Clientes from "@/components/sectionClientes/clientes";
import Endereco from "@/components/SecrionEndereço/endereco";
import Rodape from "@/components/SectionRodape/Rodape";
import Modal from "@/components/modal/modal";







export default function Home() {

  const [menu , setMenu]= useState(nav)
  const [card , setCard] = useState(array)
  const [modal , setModal] = useState(false)
  const [txInput , setTxInput] = useState('')
  const [retorno , setRetorno] = useState(styles.Desaparecer)


  const [nCard , setNovoCard] = useState(array)

  


 

  const modalRef = useRef()

  

  function MostrarModal(){

    setModal(!modal)
    setTxInput('')
    setCard(array)

    
    
  }
    


   

  function ClickOut(evento){


    if(modalRef.current && !modalRef.current.contains(evento.target)){

        setModal(!modal)


        if(card.length == 0){

          setCard(array)
         
        }
          
    }
        

  }


  useEffect(()=>{

    if(card.length === 0){

      setRetorno(styles.Msg)

    }else{

        setRetorno(styles.Desaparecer)
    }


  }, [card])
    


  function PesquisarMenu(txDigitado){

    const filtro = array.filter((array)=>
    
        array.titulo.toLowerCase().includes(txDigitado.toLowerCase())
    
    )
  
    
    let txFiltrado =  setCard(filtro)

    setTxInput(txFiltrado)

  }
    
    
  function ChangeInput(evento){

    PesquisarMenu(evento.target.value)
    

  }
  

  // function clickMenu(){

  //     const teste = nav.filter((nav)=> nav === nav)

  //     console.log(teste)

  // }
     

    

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      

        <header>
          <Topo
        
          naveg ={menu}
          clickModal={MostrarModal}
          clickOut={ClickOut}
          // clickMenu={clickMenu}
         
          />
        
        </header>
        
        
        <main className={`${styles.Main}`} onClick={ClickOut} >

        <Modal
        
        statusModal={modal}
        clickModal={MostrarModal}
        referencia={modalRef}
        clickOut={ClickOut}
        txInput={txInput}
        change={ChangeInput}
        pesquisa={PesquisarMenu}

        card={card}

        
        />
        
        
      
         
        

        <SectionCafe/>
        
        
        <SobreNos/>


        <Menu

          card={card}
          statusModal={modal}
          status={retorno}
        />
    
            
        <Clientes/>

        <Endereco/>

            

        </main>
          
        
        <footer>

            <Rodape/>

        </footer>
        
        
        
        
     
    </>
  );
}
